### ISSUE TITLE
e-TOF trace initial processing

### ISSUE THREAD

**Issue by shortcirc** [pnjun/Thionuracil-Analysis#1]
slicing e-TOF traces to cut out dead time between macrobunches and shots -> filesize reduction
converting e-TOF traces to kinetic energy scale

**Comment by shortcirc** [comment]
update wiki about data structure for collaborators

**Comment by pnjun** [comment]
We also need some kind of shared folder to write the processed data into

**Comment by gveard** [comment]
Well, the directory for our beamtime contains also a "processed" and "shared" folder. We should have writing permissions for at least the "shared" folder. So, it might be an option to store it there if there is no storage limitation...

**Comment by shortcirc** [comment]
Don't know about storage size. Should have asked Stefan in my email about OPIS and laser trace. I'll ask im when he replies. "processed" sounds logic to me.
If we hit the limit we can still mygrate to our NAS or the evaluation mashine in my office in the worst case.

**Comment by pnjun** [comment]
dataPreprocessing is now working. We just need to fine tune slicing offsets. I will next try to analyze the OPIS data directly.

Tell me if you need more columns in the processed data
